import { JOBS, STAT_CAP, STAT_KEYS, calculateStats, getExperienceForLevel, getLevelGrowth, previewStatChange } from "./growth-model.js?v=20260719-2";
for (const href of ["./typography.css?v=20260719-1", "./desktop-layout.css?v=20260719-2"]) { const stylesheet = document.createElement("link"); stylesheet.rel = "stylesheet"; stylesheet.href = href; document.head.append(stylesheet); }
const LABELS = Object.freeze({ str: "STR", int: "INT", agi: "AGI", dex: "DEX", luc: "LUC" }); const state = { jobId: "warrior", level: 1, equipment: {}, cards: {} }; const $ = (selector) => document.querySelector(selector); const pad = (value, length) => String(value).padStart(length, "0");
function buildControls() {
  $("#jobSelect").replaceChildren(...Object.entries(JOBS).map(([id, job]) => { const option = document.createElement("option"); option.value = id; option.textContent = `${job.name} / ${job.nameJa}`; return option; }));
  $("#previewStat").replaceChildren(...STAT_KEYS.map((key) => { const option = document.createElement("option"); option.value = key; option.textContent = LABELS[key]; return option; }));
  const fragment = document.createDocumentFragment();
  for (const key of STAT_KEYS) { const label = document.createElement("strong"); label.textContent = LABELS[key]; fragment.append(label); for (const source of ["equipment", "cards"]) { const input = document.createElement("input"); input.type = "number"; input.min = "0"; input.max = "30"; input.value = "0"; input.dataset.stat = key; input.dataset.source = source; input.setAttribute("aria-label", `${LABELS[key]} ${source}`); fragment.append(input); } }
  $("#bonusInputs").append(fragment);
}
function createStatRow(key, values) {
  const row = document.createElement("div"); row.className = `stat-row${values.total > STAT_CAP ? " is-over" : ""}`; const label = document.createElement("strong"); label.textContent = LABELS[key]; const gauge = document.createElement("div"); gauge.className = "gauge"; gauge.setAttribute("aria-label", `${LABELS[key]} ${values.total}/${STAT_CAP}`);
  for (let index = 0; index < STAT_CAP; index += 1) { const cell = document.createElement("i"); if (index < values.base) cell.className = "base"; else if (index < values.base + values.equipment) cell.className = "equipment"; else if (index < Math.min(values.total, STAT_CAP)) cell.className = "cards"; gauge.append(cell); }
  const total = document.createElement("output"); total.textContent = String(values.total).padStart(2, "0"); row.append(label, gauge, total); return row;
}
function render() { const calculated = calculateStats(state); const growth = getLevelGrowth(state.jobId, state.level); const job = JOBS[state.jobId]; $("#jobName").textContent = job.name; $("#levelOutput").textContent = pad(growth.level, 3); $("#levelValue").textContent = growth.level; $("#hpOutput").textContent = `${pad(growth.hp, 3)} / ${pad(growth.hp, 3)}`; $("#spOutput").textContent = `${pad(growth.sp, 3)} / ${pad(growth.sp, 3)}`; $("#deckCost").textContent = growth.deckCost; $("#experience").textContent = `${pad(getExperienceForLevel(growth.level), 7)} / 9999999`; $("#statRows").replaceChildren(...STAT_KEYS.map((key) => createStatRow(key, calculated.stats[key]))); }
function checkPreview() { const source = $("#previewSource").value; const key = $("#previewStat").value; const amount = Math.max(0, Number($("#previewAmount").value) || 0); const preview = previewStatChange(state, source, { [key]: amount }); const value = preview.result.stats[key].total; const message = $("#previewMessage"); message.classList.toggle("denied", !preview.allowed); message.textContent = preview.allowed ? `${LABELS[key]} ${value}/${STAT_CAP} — 装着可能` : `${LABELS[key]} ${value}/${STAT_CAP} — 装着不可（上限オーバー）`; }
buildControls(); render(); $("#jobSelect").addEventListener("change", (event) => { state.jobId = event.target.value; render(); }); $("#levelInput").addEventListener("input", (event) => { state.level = Number(event.target.value); render(); }); $("#bonusInputs").addEventListener("input", (event) => { const { stat, source } = event.target.dataset; if (!stat) return; state[source][stat] = Math.max(0, Number(event.target.value) || 0); render(); }); for (const id of ["previewButton", "previewAmount", "previewStat", "previewSource"]) $("#" + id).addEventListener(id === "previewButton" ? "click" : "input", checkPreview);
