import { calculateStats } from "../growth-system/growth-model.js?v=20260719-2";
const LABELS={str:"STR",int:"INT",agi:"AGI",dex:"DEX",luc:"LUC",def:"DEF"};
const build={jobId:"warrior",equipment:{str:2,agi:1,luc:1},cards:{str:3,agi:1,dex:1}};
const returnTarget=new URLSearchParams(location.search).get("return");let pageIndex=0;
function createStatRow(key,v){const row=document.createElement("div");row.className="stat-row";const label=document.createElement("strong");label.textContent=LABELS[key];const gauge=document.createElement("div");gauge.className="gauge";gauge.setAttribute("aria-label",`${LABELS[key]} ${v.total}/30`);for(let i=0;i<30;i+=1){const cell=document.createElement("i");if(i<v.base)cell.className="base";else if(i<v.base+v.equipment)cell.className="equipment";else if(i<v.total)cell.className="cards";gauge.append(cell)}const total=document.createElement("output");total.textContent=String(v.total).padStart(2,"0");row.append(label,gauge,total);return row}
function setPage(next){pageIndex=Math.max(0,Math.min(1,next));document.querySelectorAll("[data-page]").forEach(page=>{page.hidden=Number(page.dataset.page)!==pageIndex});document.querySelector("#pageIndicator").textContent=`${pageIndex+1}/2`;document.querySelector('.pager [data-action="back"]').classList.toggle("is-selected",pageIndex===0);document.querySelector('.pager [data-action="next"]').classList.toggle("is-selected",pageIndex===1)}
function act(action){if(action==="back"&&pageIndex===0&&returnTarget){location.href=returnTarget;return}setPage(action==="next"?pageIndex+1:pageIndex-1)}
function confirmSelection(){act(pageIndex===0?"back":"next")}
const calculated=calculateStats(build);const rows=Object.entries(calculated.stats).map(([key,v])=>createStatRow(key,v));rows.push(createStatRow("def",{base:5,equipment:6,cards:0,total:11}));document.querySelector("#statRows").replaceChildren(...rows);
document.querySelectorAll(".pager [data-action]").forEach(button=>button.addEventListener("click",()=>act(button.dataset.action)));
document.querySelector("#statusButtonA").addEventListener("click",confirmSelection);document.querySelector("#statusButtonB").addEventListener("click",()=>act("back"));
window.addEventListener("keydown",event=>{if(event.key==="ArrowRight")act("next");if(event.key==="ArrowLeft"||["Escape","z","Z"].includes(event.key))act("back");if(["Enter","x","X"].includes(event.key))confirmSelection()});
const stick=document.querySelector("#virtualStick"),knob=stick.querySelector(".virtual-stick-knob");let pointerId=null,centerX=0,triggered=false;stick.addEventListener("pointerdown",event=>{pointerId=event.pointerId;triggered=false;const rect=stick.getBoundingClientRect();centerX=rect.left+rect.width/2;stick.setPointerCapture(pointerId)});stick.addEventListener("pointermove",event=>{if(event.pointerId!==pointerId)return;const dx=Math.max(-34,Math.min(34,event.clientX-centerX));knob.style.transform=`translateX(${dx}px)`;if(!triggered&&Math.abs(dx)>24){triggered=true;act(dx>0?"next":"back")}});function release(event){if(event.pointerId!==pointerId)return;pointerId=null;knob.style.transform="translateX(0)"}stick.addEventListener("pointerup",release);stick.addEventListener("pointercancel",release);setPage(0);
